### ISSUE TITLE
TikTok embeds not working

### ISSUE THREAD

**Issue by mariwrites** [podaboutlist/linkfix-for-discord#91] opened 2024-05-17 08:06 UTC
Not much to say, the bot simply does not embed TikTok links. Its been happening for two days now. It will still generate a link but it won’t embed the video. 

Thank yoj,
Mari

**Comment by shoegaze** [comment] 2024-05-19 12:39
Hi Mari, thank you for the heads up! I just tested some TikTok links and I can confirm they're not being embedded properly. We'll be look into it further.

@RalphORama Looks like TikTok changed its API and broke `fxTikTok`
See: https://github.com/okdargy/fxTikTok/issues/7 and https://github.com/imputnet/cobalt/issues/497

Might have to hotfix the above as a temporary fix? 🤔

**Comment by okdargy** [comment] 2024-05-25 23:47
> Hi Mari, thank you for the heads up! I just tested some TikTok links and I can confirm they're not being embedded properly. We'll be look into it further.
> 
> @RalphORama Looks like TikTok changed its API and broke `fxTikTok` See: [okdargy/fxTikTok#7](https://github.com/okdargy/fxTikTok/issues/7) and [imputnet/cobalt#497](https://github.com/imputnet/cobalt/issues/497)
> 
> Might have to hotfix the above as a temporary fix? 🤔

Just wanted to pop in and say that [fxTikTok](https://github.com/okdargy/fxTikTok) has been fixed and it seems like [vxtiktok](https://github.com/dylanpdx/vxtiktok) also pushed a fix but still doesn't have full support for slideshows which is reasonable since they do have a custom [ffmpeg slideshow builder](https://github.com/dylanpdx/vxtiktok/blob/main/slideshowBuilder/__init__.py)

**Comment by mariwrites** [comment] 2024-05-26 02:04
Hello,

It doesn’t seem to be fixed in my end. I’ll attach a picture of me trying
to use it just now.


Hope this helps and that you are able to fix the problem!

Best wishes,
Mari

.

**Comment by ruukulada** [comment] 2024-06-06 18:31
Can we switch to [https://tfxktok.com](https://tfxktok.com)?
I find that vxtiktok links only work on desktop, not on mobile.

**Comment by RalphORama** [comment] 2024-06-13 16:21
Confirming this looks like an issue with vxtiktok. I'll configure the bot to use `tfxktok.com` and push an update for default config files soon™

**Closed** 2024-10-30 17:31 UTC
Labels: bug, in progress, replacements
